import type { Metadata } from 'next'
import { Geist_Mono, Syne } from 'next/font/google'
import './globals.css'
import AppNavbar from '@/components/layout/app-navbar'

const syne = Syne({
	variable: '--font-syne',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700', '800']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${syne.variable} ${geistMono.variable} min-h-screen font-sans antialiased`}>
				<AppNavbar />
				<div className="relative min-h-screen">
					<main className="relative z-10">{children}</main>
				</div>
			</body>
		</html>
	)
}
